org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
mod_id=abstool
mod_name=Ab's Tool
mod_version=0.4.9
mod_group_id=com.abyssredemption.abstool
minecraft_version=26.2
neo_version=26.2.0.77
loader_version=0.19.5
fabric_api_version=0.159.0+26.2
cloth_config_version=26.2.155
modmenu_version=20.0.2
