org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
mod_id=abstool
mod_name=Ab's Tool
mod_version=0.5.0-beta.2
mod_group_id=com.abyssredemption.abstool
minecraft_version=26.3
neo_version=26.3.0.23-beta
loader_version=0.19.5
fabric_api_version=0.160.6+26.3
cloth_config_version=26.3.158
modmenu_version=21.0.0
