pluginManagement {
    repositories {
        maven { url = 'https://maven.neoforged.net/releases' }
        maven { url = 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
    }
}

rootProject.name = 'abstool-26.3'
include 'neoforge', 'fabric'
project(':neoforge').projectDir = file('26.3NeoForge')
project(':fabric').projectDir = file('26.3Fabric')
