package com.abyssredemption.abstool.client.serverstats.gui;
import com.abyssredemption.abstool.client.serverstats.*; import com.abyssredemption.abstool.client.serverstats.model.*; import com.abyssredemption.abstool.client.serverstats.network.*; import net.minecraft.client.gui.GuiGraphicsExtractor; import net.minecraft.client.gui.components.Button; import net.minecraft.client.gui.screens.Screen; import net.minecraft.network.chat.Component;
public final class ServerStatsScreen extends Screen { private final Screen parent; private LeaderboardType type=LeaderboardType.PLAYTIME; private int page=1; private Button previous,next,refresh;
 public ServerStatsScreen(Screen p){super(Component.translatable("abstool.serverstats.title"));parent=p;}
 protected void init(){super.init();int x=width/2-190;for(LeaderboardType t:LeaderboardType.values()){LeaderboardType selected=t;addRenderableWidget(Button.builder(Component.literal(label(t)),b->{if(ServerStatsClient.state().supports(selected)){type=selected;page=1;ServerStatsClient.request(type,page,false);}}).bounds(x,58,92,20).build());x+=96;} previous=addRenderableWidget(Button.builder(Component.literal("上一页"),b->{if(page>1){page--;ServerStatsClient.request(type,page,false);}}).bounds(width/2-100,height-35,70,20).build());next=addRenderableWidget(Button.builder(Component.literal("下一页"),b->{var d=ServerStatsClient.state().get(type,page);if(d!=null&&page<d.totalPages()){page++;ServerStatsClient.request(type,page,false);}}).bounds(width/2+30,height-35,70,20).build());refresh=addRenderableWidget(Button.builder(Component.literal("刷新"),b->ServerStatsClient.request(type,page,true)).bounds(width-155,height-35,65,20).build());addRenderableWidget(Button.builder(Component.literal("关闭"),b->onClose()).bounds(width-85,height-35,65,20).build());ServerStatsClient.request(type,page,false);}
 private static String label(LeaderboardType t){return switch(t){case PLAYTIME->"在线时间";case DEATHS->"死亡次数";case BLOCKS_TOTAL->"总放置量";case BLOCKS_WEEKLY->"本周放置量";};}
 public void extractRenderState(GuiGraphicsExtractor g,int mx,int my,float pt){super.extractRenderState(g,mx,my,pt);var text=g.textRenderer();text.accept(width/2-45,25,title);var s=ServerStatsClient.state();String status=s.availability()==ServerStatsAvailability.READY?"已连接":"状态："+s.availability();text.accept(width/2-180,42,Component.literal(status));var d=s.get(type,page);if(d==null){text.accept(width/2-70,110,Component.literal(status.equals("已连接")?"正在加载...":status));return;}int y=105;for(ClientLeaderboardEntry e:d.entries()){text.accept(width/2-180,y,Component.literal(String.format("%d  %-24s  %d%s",e.rank(),e.playerName(),e.value(),e.online()?"  ●":"")));y+=18;}text.accept(width/2-45,height-55,Component.literal("第 "+page+" / "+d.totalPages()+" 页"));}
 public void onClose(){minecraft.setScreenAndShow(parent);}
}
