package com.abyssredemption.abstool.client.serverstats;
import com.abyssredemption.abstool.client.serverstats.gui.ServerStatsScreen; import com.abyssredemption.abstool.client.serverstats.model.*; import com.abyssredemption.abstool.client.serverstats.network.*; import com.abyssredemption.abstool.client.serverstats.network.payload.*; import net.minecraft.client.*; import net.neoforged.neoforge.client.event.ClientTickEvent; import net.neoforged.neoforge.client.network.ClientPacketDistributor; import net.neoforged.neoforge.network.event.RegisterPayloadHandlersEvent; import net.neoforged.neoforge.network.registration.PayloadRegistrar; import java.util.*;
public final class ServerStatsClient { private static final ServerStatsState STATE=new ServerStatsState(); private static long nextId; private static int checks,ticks; private ServerStatsClient(){} public static ServerStatsState state(){return STATE;}
 public static void register(RegisterPayloadHandlersEvent e){PayloadRegistrar r=e.registrar("2").optional();r.playToServer(HelloRequestPayload.TYPE,HelloRequestPayload.CODEC,(p,c)->{});r.playToServer(OverviewRequestPayload.TYPE,OverviewRequestPayload.CODEC,(p,c)->{});r.playToServer(TrendRequestPayload.TYPE,TrendRequestPayload.CODEC,(p,c)->{});r.playToServer(LeaderboardRequestPayload.TYPE,LeaderboardRequestPayload.CODEC,(p,c)->{});r.playToClient(HelloResponsePayload.TYPE,HelloResponsePayload.CODEC,(p,c)->onHello(p));r.playToClient(OverviewResponsePayload.TYPE,OverviewResponsePayload.CODEC,(p,c)->onOverview(p));r.playToClient(TrendResponsePayload.TYPE,TrendResponsePayload.CODEC,(p,c)->onTrend(p));r.playToClient(LeaderboardResponsePayload.TYPE,LeaderboardResponsePayload.CODEC,(p,c)->onBoard(p));r.playToClient(StatsErrorPayload.TYPE,StatsErrorPayload.CODEC,(p,c)->STATE.availability(ServerStatsAvailability.ERROR));}
 public static void tick(ClientTickEvent.Post e){Minecraft mc=Minecraft.getInstance();if(mc.getConnection()==null){if(STATE.availability()!=ServerStatsAvailability.UNKNOWN)STATE.clear();checks=0;ticks=0;return;}if(STATE.availability()==ServerStatsAvailability.UNKNOWN&&ticks++%20==0&&checks<3){checks++;if(mc.getConnection().hasChannel(HelloRequestPayload.TYPE.id())){STATE.availability(ServerStatsAvailability.CHECKING);ClientPacketDistributor.sendToServer(new HelloRequestPayload(ProtocolConstants.VERSION));}else if(checks>=3)STATE.availability(ServerStatsAvailability.UNSUPPORTED);}}
 private static void onHello(HelloResponsePayload p){if(p.protocolVersion()!=ProtocolConstants.VERSION){STATE.availability(ServerStatsAvailability.PROTOCOL_MISMATCH);return;}STATE.hello(p.capabilities(),p.trackingStartedDate(),p.timezone(),p.todayPartial());requestOverview(true);}
 private static void onOverview(OverviewResponsePayload p){if(p.protocolVersion()!=ProtocolConstants.VERSION||p.onlinePlayers()<0||p.knownPlayers()<0||p.dau()<0||p.wau()<0)return;STATE.putOverview(new ServerOverview(p.dateKey(),p.weekKey(),p.onlinePlayers(),p.knownPlayers(),p.dau(),p.wau(),p.todayPlayTimeTicks(),p.weekPlayTimeTicks(),p.todayPlacements(),p.weekPlacements(),p.todayDeaths(),p.weekDeaths(),p.todayPartial(),p.weekPartial(),p.generatedAtMillis()),p.requestId());}
 private static void onTrend(TrendResponsePayload p){if(p.protocolVersion()!=ProtocolConstants.VERSION||p.entries().size()>ProtocolConstants.MAX_DAILY_TREND)return;STATE.putTrend(p.periodType(),p.entries(),p.requestId());}
 private static void onBoard(LeaderboardResponsePayload p){if(p.protocolVersion()!=ProtocolConstants.VERSION||p.totalPages()<1||p.page()<1||p.totalEntries()<0||p.entries().size()>ProtocolConstants.MAX_ENTRIES)return;var t=LeaderboardType.fromNetworkId(p.leaderboardType());if(t.isEmpty())return;List<ClientLeaderboardEntry> es=p.entries().stream().map(e->new ClientLeaderboardEntry(e.rank(),e.uuid(),e.playerName().isBlank()?"未知玩家":e.playerName(),Math.max(0,e.value()),e.online())).toList();STATE.put(new ClientLeaderboardPage(t.get(),p.page(),p.totalPages(),p.totalEntries(),p.generatedAtEpochMillis(),p.contextLabel(),es),p.requestId());}
 public static void requestOverview(boolean force){if(STATE.availability()==ServerStatsAvailability.READY&&(force||STATE.overview()==null)){long id=++nextId;STATE.expect("overview",id);ClientPacketDistributor.sendToServer(new OverviewRequestPayload(ProtocolConstants.VERSION,id));}}
 public static void requestTrend(int period,int count,boolean force){if(STATE.availability()==ServerStatsAvailability.READY&&(!force&&STATE.freshTrend(period)))return;if(STATE.availability()==ServerStatsAvailability.READY){long id=++nextId;STATE.expect("trend:"+period,id);ClientPacketDistributor.sendToServer(new TrendRequestPayload(ProtocolConstants.VERSION,id,period,count));}}
 public static void request(LeaderboardType t,int page,boolean force){page=Math.max(1,page);if(STATE.availability()==ServerStatsAvailability.READY&&STATE.supports(t)&&(force||!STATE.fresh(t,page))){long id=++nextId;STATE.expect(t+":"+page,id);ClientPacketDistributor.sendToServer(new LeaderboardRequestPayload(ProtocolConstants.VERSION,id,t.networkId(),page));}}
 public static void open(){Minecraft mc=Minecraft.getInstance();if(mc.getConnection()!=null)mc.setScreenAndShow(new ServerStatsScreen(null));}
}
