package com.abyssredemption.abstool.client.serverstats;
import com.abyssredemption.abstool.client.serverstats.model.*; import com.abyssredemption.abstool.client.serverstats.network.*; import java.util.*;
public final class ServerStatsState {
 private ServerStatsAvailability availability=ServerStatsAvailability.UNKNOWN; private int capabilities; private String trackingStartedDate="",timezone=""; private boolean todayPartial; private ServerOverview overview; private long overviewRequestId; private final Map<Integer,List<TrendEntry>> trends=new HashMap<>(); private final Map<Integer,Long> trendReceived=new HashMap<>(); private final Map<String,ClientLeaderboardPage> pages=new HashMap<>(); private final Map<String,Long> received=new HashMap<>(); private final Map<String,Long> requests=new HashMap<>();
 public ServerStatsAvailability availability(){return availability;} public void availability(ServerStatsAvailability a){availability=a;} public int capabilities(){return capabilities;} public String timezone(){return timezone;} public String trackingStartedDate(){return trackingStartedDate;} public boolean todayPartial(){return todayPartial;} public ServerOverview overview(){return overview;} public List<TrendEntry> trend(int period){return trends.getOrDefault(period,List.of());}
 public void hello(int c,String started,String zone,boolean partial){capabilities=c;trackingStartedDate=started;timezone=zone;todayPartial=partial;availability=ServerStatsAvailability.READY;} public void clear(){pages.clear();received.clear();requests.clear();trends.clear();trendReceived.clear();overview=null;overviewRequestId=0;availability=ServerStatsAvailability.UNKNOWN;capabilities=0;trackingStartedDate="";timezone="";todayPartial=false;}
 public void expect(String key,long id){requests.put(key,id);} public boolean accepts(String key,long id){return requests.getOrDefault(key,-1L)==id;} public void putOverview(ServerOverview o,long id){if(accepts("overview",id)){overview=o;overviewRequestId=id;}} public void putTrend(int period,List<TrendEntry> e,long id){if(accepts("trend:"+period,id)){trends.put(period,e);trendReceived.put(period,System.currentTimeMillis());}} public boolean freshTrend(int period){return System.currentTimeMillis()-trendReceived.getOrDefault(period,0L)<30000;}
 public void put(ClientLeaderboardPage p,long id){String k=p.type()+":"+p.page();if(accepts(k,id)){pages.put(k,p);received.put(k,System.currentTimeMillis());}} public ClientLeaderboardPage get(LeaderboardType t,int p){return pages.get(t+":"+p);} public boolean fresh(LeaderboardType t,int p){return System.currentTimeMillis()-received.getOrDefault(t+":"+p,0L)<10000;}
 public boolean supports(LeaderboardType t){int bit=switch(t){case TOTAL_PLAYTIME,TODAY_PLAYTIME,WEEK_PLAYTIME->ProtocolConstants.CAP_PLAYTIME;case TOTAL_DEATHS,TODAY_DEATHS,WEEK_DEATHS->ProtocolConstants.CAP_DEATHS;case TOTAL_PLACEMENTS,TODAY_PLACEMENTS,WEEK_PLACEMENTS->ProtocolConstants.CAP_PLACEMENTS;};return (capabilities&bit)!=0;}
}
